Drag zoom
palantir/plottable pull request #3136
Opened 2016-12-09 23:13 UTC by CalvinFernandez

This is something we still want -- rebasing @danmane's original pr

2017-01-05 22:37 UTC, themadcreator requested changes

2017-01-05 22:37 UTC, themadcreator commented on src/components/dragZoomLayer.ts
> +        this.yDomainToRestore = this.yScale().domain();
Is it possible the domain will change after the scale is zoomed? These may become out of date

2017-01-05 22:37 UTC, themadcreator commented on src/components/dragZoomLayer.ts
> +    // If we are zooming, disable interactions, to avoid contention
Cool, but will other interactions contend as well?

2017-01-05 22:37 UTC, themadcreator commented on src/components/dragZoomLayer.ts
> +        this.yScale().domain([y0, y1]);
This doesn't respect max zoom extents. Could we instead use the PanZoomInteraction now that we expose the .zoom method?

2017-01-05 22:37 UTC, themadcreator commented on src/components/dragZoomLayer.ts
> +    constructor(xScale: QuantitativeScale<Numeric>,
now that Category scales support pan/zoom maybe we could instead pass a panzoominteraction here? Or pass in TransformableScale types?

2017-01-05 22:44 UTC, hellochar commented on src/core/interfaces.ts
> +export type Numeric = number | {valueOf(): number};
I'm guessing the point of having this type is to accept number or Date objects? I dug around a lot but couldn't find a clear answer.

2017-01-05 22:44 UTC, hellochar commented on src/components/dragZoomLayer.ts
> +      this._doubleClickInteraction.onDoubleClick(() => this.unzoom());
this adds double-click to unzoom; we should call that out

2017-01-05 22:44 UTC, hellochar commented on src/components/dragZoomLayer.ts
> +      let draw = () => {
Wonder if we should be implementing our own animation logic here instead of using a Plottable.Animator

2017-02-06 11:56 UTC, adidahiya commented
Is this still relevant? If not, please close as this is getting pretty stale.

2017-02-13 22:45 UTC, closed without merging