PanZoom: Expose Zoom and Pan Api
palantir/plottable pull request #3146
Opened 2017-01-05 20:31 UTC by CalvinFernandez

Expose pan and zoom api to allow users to imperatively pan and
zoom the chart independently of the mousewheel or pinch events.

closes #3141

2017-01-05 20:56 UTC, themadcreator requested changes
Conflicts incoming

2017-01-05 20:56 UTC, themadcreator commented on src/interactions/panZoomInteraction.ts
> +    public pan(translateAmount: Plottable.Point) {
I think this is going to conflict with the changes I made to enable pan/zoom on category scales. So, can we wait until that other is merged? I can pull this down and update the PR once it's merged.

2017-01-05 21:04 UTC, CalvinFernandez commented on src/interactions/panZoomInteraction.ts
> +    public pan(translateAmount: Plottable.Point) {
yep noticed major conflicts -- I'm totally fine waiting

2017-01-05 22:26 UTC, themadcreator approved these changes

2017-01-05 22:46 UTC, hellochar approved these changes

2017-01-05 23:02 UTC, merged

2017-01-10 19:09 UTC, contra commented
Are there any docs live for this yet? Couldn't find any.

2017-01-13 17:04 UTC, CalvinFernandez commented
@contra working on this now sorry for the delay

2017-01-13 17:10 UTC, contra commented
@CalvinFernandez No prob, just wondering if I was missing something - I thought the docs were autogenerated from the source