add tickLabelMaxLines property to category scale
palantir/plottable pull request #3155
Opened 2017-01-11 01:06 UTC by hellochar

Allows fine grained control over how many lines the tick label should be.

**Warning**: This modifies the existing behavior of `tickLabelMaxWidth` -- when set, maxLines no longer defaults to 1. Instead, maxLines is fully controlled by `tickLabelMaxLines`.

2017-01-12 21:32 UTC, themadcreator requested changes

2017-01-12 21:32 UTC, themadcreator commented on plottable.js
> -                    if (this._tickLabelMaxWidth != null) {
We default back to 1 if _tickLabelMaxLines isn't set, right?

2017-01-12 21:32 UTC, themadcreator commented on src/axes/categoryAxis.ts
> +        wrapper.maxLines(this._tickLabelMaxLines)
Same

2017-01-13 00:21 UTC, hellochar commented on plottable.js
> -                    if (this._tickLabelMaxWidth != null) {
No, we now don't have any defaults. I felt it was simpler from an API perspective

2017-01-13 00:22 UTC, hellochar commented on src/axes/categoryAxis.ts
> +        wrapper.maxLines(this._tickLabelMaxLines)
This is the same code as the one in plottable.js; I committed the built file as well

2017-01-16 18:40 UTC, themadcreator commented on src/axes/categoryAxis.ts
> +        wrapper.maxLines(this._tickLabelMaxLines)
Ah, right. Okay well I'm fine so long as it's on purpose.

2017-01-16 18:40 UTC, themadcreator approved these changes

2017-01-16 18:45 UTC, merged