Add alignment and start/end angle to pie plots
palantir/plottable pull request #3156
Opened 2017-01-11 16:34 UTC by carlosdiazh

Addresses issue [#1041](https://github.com/palantir/plottable/issues/1041)

Adding to pie plot: 
- `startAngle(angle: number)`:  sets the start angle, so pies do not need to be a complete circle
- `endAngle(angle: number)` : sets the end angle, so pies do not need to be a complete circle
- `hAlign(alignment: string)`: the alignment is by default in the center of the render area. using `"left"` or `"right"` you can align the horizontal axis to the left or the right
- `vAlign(alignment: string)`: the alignment is by default in the center of the render area. using `"top"` or `"bottom"` you can align the vertical axis to the top or the bottom.

2017-01-11 16:34 UTC, palantirtech commented
Thanks for your interest in [palantir/plottable](https://github.com/palantir/plottable), @carlosdiazh! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2017-01-11 23:19 UTC, hellochar requested changes
Thanks for the PR @carlosdiazh ! 

Code looks pretty straightforward, but I'm not sure I understand the purpose of hAlign/vAlign. Pie plots don't have vertical or horizontal axes. The code looks like it just shifts the entire pie within the rendering area?

2017-01-11 23:19 UTC, hellochar commented on test/plots/piePlotTests.ts
> +        assert.operator(moveCommand0.arguments[1], ">", 0, "starts first arc at the bottom of circle (y)");
nit: I find assert.isAbove and assert.isBelow slightly more readable

2017-01-11 23:19 UTC, hellochar commented on src/plots/piePlot.ts
> +     * Gets whether slice labels are enabled.
update docs here

2017-01-11 23:19 UTC, hellochar commented on src/plots/piePlot.ts
> +      let factor = (this.endAngle() - this.startAngle()) / (2 * Math.PI);
Looks like d3.layout.pie has something similar already: see https://github.com/d3/d3-3.x-api-reference/blob/master/Pie-Layout.md#startAngle . Can we take advantage of that?

2017-01-12 09:50 UTC, carlosdiazh commented
@hellochar The purpose of `hAlign` and `vAlign` is to be able to place the center of the pie in one of the sides of the render area, so that when you are drawing a half pie, half of the render area isn't left out blank. This is the only thing I could think of, but if there is something else I could use I'd be happy to change it

2017-01-12 20:51 UTC, hellochar commented
Ah I see - so you mean when setting startAngle/endAngle by itself, you'll get pies that only cover half the area: 
![image](https://cloud.githubusercontent.com/assets/1079495/21907600/25d3f440-d8de-11e6-9e1b-60fe84fbf746.png)

In order to fix that, users can do `vAlign("top")` to push it to the top: 
![image](https://cloud.githubusercontent.com/assets/1079495/21907649/5f4321f6-d8de-11e6-858d-67f3a6c30961.png)

But won't that have the same issue where the second half of the chart is completely empty? Furthermore, you never want to use `hAlign/vAlign` by itself (otherwise the pie would escape its drawing boundary); you only want to set them to certain values in combination of `startAngle`/`endAngle`, is that right? I'm worried that exposing this API surface area will confuse users since it's not obvious what it does/what it's used for. 

How would you feel about auto-scaling the pie chart to fill the plot width/height depending on the start/endAngle?

@CalvinFernandez @themadcreator thoughts?

2017-01-13 17:01 UTC, CalvinFernandez reviewed
This is great! Thanks for the PR @carlosdiazh! re: @hellochar's comment, I think one solution could be to adjust the size of the component during the space negotiation phase to ensure that the chart always correctly fills the plot area. Also not a huge fan of `hAlign/vAlign` .  I'm also fine with just leaving the second half of the chart completely empty and revisiting this as a follow up commit.

2017-01-13 17:01 UTC, CalvinFernandez commented on src/plots/piePlot.ts
> +     * Sets the end angle of the Pie Plot.
Sets the ~end~ start angle of the Pie Plot

2017-01-13 17:01 UTC, CalvinFernandez commented on src/plots/piePlot.ts
> +     * @param {number} endAngle
~endAngle~ start angle

2017-01-13 17:01 UTC, CalvinFernandez commented on src/plots/piePlot.ts
> +     * @returns {boolean} Whether slices should display labels or not.
string

2017-01-16 20:25 UTC, hellochar requested changes
Thanks for removing hAlign/vAlign. Feels close now; just some polish on the new pie centering logic

2017-01-16 20:25 UTC, hellochar commented on src/plots/piePlot.ts
> +      this._renderArea.attr("transform", "translate(" + pieCenter.x + "," + pieCenter.y + ")");
We should update the transform in the minAngle/maxAngle setter, not just in `computeLayout`

2017-01-16 20:25 UTC, hellochar commented on src/plots/piePlot.ts
> +      let a = this._startAngle < this._endAngle ? this._startAngle: this._endAngle;
Holy cow this is impressive. Can we add comments to describe what's going on? Is there a way to reduce the number of if/elses?

2017-01-17 08:56 UTC, carlosdiazh commented on src/plots/piePlot.ts
> +      let a = this._startAngle < this._endAngle ? this._startAngle: this._endAngle;
Sure, I'll add some comments. 
I've been trying to come up with a more generic way to compute the center but I haven't been able to find anything that doesn't leave out some possibilities potentially cutting out part of the pie.

2017-01-17 13:00 UTC, carlosdiazh commented on src/plots/piePlot.ts
> +      this._renderArea.attr("transform", "translate(" + pieCenter.x + "," + pieCenter.y + ")");
I tried doing this, but `this._renderArea` is still undefined

2017-01-17 13:05 UTC, carlosdiazh commented on src/plots/piePlot.ts
> +      let a = this._startAngle < this._endAngle ? this._startAngle: this._endAngle;
I've added a general comment, above the if/elses, it's a bit hard to explain exactly whats going on on each condition without drawing. Hopefully this'll do. Let me know though. 

We could also get rid of the last if on each block but I feel like stating the condition makes it easier to understand so one can picture in their head the image of the area of the whole circle the pie should take.

2017-01-17 19:27 UTC, hellochar approved these changes

2017-01-17 19:27 UTC, merged

2017-01-17 19:33 UTC, hellochar commented
Looks great, thanks @carlosdiazh !

2017-01-17 22:34 UTC, hellochar commented
Oops, let https://github.com/palantir/plottable/issues/3168 through...