Update svg-typewriter
palantir/plottable pull request #3164
Opened 2017-01-16 23:31 UTC by themadcreator

* Switch to npm package
* Update build scripts
* Use CacheMeasurer everywhere for PERFORMANCE!

2017-01-16 23:32 UTC, themadcreator commented
Check out this buttery smooth pan/zoom

![smooth-zoom](https://cloud.githubusercontent.com/assets/569364/22002428/e6933a9a-dc00-11e6-8cd5-503eab051eca.gif)

2017-01-17 17:16 UTC, CalvinFernandez submitted a review, later dismissed
Good idea! Unfortunately we need to keep svg-typewriter bundled for now as it will break all standalone builds. We tried this a month or so ago and reverted

2017-01-17 18:04 UTC, adidahiya commented
this is the relevant discussion btw https://github.com/palantir/plottable/pull/3119

2017-01-17 20:29 UTC, hellochar requested changes
I tried running tests but it errored from not being able to find svg-typewriter :(

2017-01-17 20:29 UTC, hellochar commented on Gruntfile.js
> -    svgtypewriter: {
We need to keep concatting this. Imo until we Plottable 3.0.0 and convert everything to modules, we need to build an svgtypewriter bundle file and concat it (or use webpack and create a plottable.js bundle, which is equivalent)

2017-01-17 20:29 UTC, hellochar commented on src/axes/categoryAxis.ts
> +      this._measurer = new SVGTypewriter.CacheMeasurer(this._tickLabelContainer);
Later on in this file we call _measurer.reset() whenever the chart is redrawn:

https://github.com/palantir/plottable/blob/bd/update-svg-typewriter/src/axes/categoryAxis.ts#L345

Will this blow away our caching improvements?

2017-01-18 21:16 UTC, themadcreator commented on src/axes/categoryAxis.ts
> +      this._measurer = new SVGTypewriter.CacheMeasurer(this._tickLabelContainer);
Yes, it clears the cache

2017-01-18 21:17 UTC, themadcreator commented on src/axes/categoryAxis.ts
> +      this._measurer = new SVGTypewriter.CacheMeasurer(this._tickLabelContainer);
But the cache is still useful because it can still be reused for common substrings while measuring

2017-01-19 02:11 UTC, hellochar requested changes
Just devtested this and had to add `@types/d3` as a dependency before it could get picked up by a client. Additionally the client had to remove `@types/d3` from its dependencies (or else typescript would see two typings). I'm okay with just pulling in `@types/d3` as a dependency, although there's some discussion over where it belongs (cc @adidahiya )

Other than that it looked good and actually fixed a long standing (been there since v1.0.0) bug where labels sometimes disappeared.

2017-01-19 05:56 UTC, adidahiya commented
`@types/d3` should be a dependency in package.json with a floating version range. I think an ideal implementation of Plottable would keep the API surface small and not leak that type to consumers in .d.ts files, but it doesn't seem like we're at a point where we can do that.

2017-01-19 19:41 UTC, themadcreator commented
`@types/d3` is already a dependency of svg-typewriter, so it should have been brought in.

2017-01-19 19:48 UTC, CalvinFernandez approved these changes

2017-01-19 20:09 UTC, hellochar approved these changes

2017-01-19 20:11 UTC, merged