add license header to source files
palantir/plottable pull request #3206
Opened 2017-02-03 21:18 UTC by hellochar

now that we release modules, all source files (that get compiled into
the /build folder) should have license headers.

2017-02-04 20:26 UTC, CalvinFernandez commented on license_header.txt
> +Copyright 2014-present Palantir Technologies
is this correct?

2017-02-06 18:15 UTC, hellochar commented on license_header.txt
> +Copyright 2014-present Palantir Technologies
Yeah I think "present" is an acceptable thing to put here; @themadcreator @adidahiya ?

2017-02-06 19:05 UTC, themadcreator commented on license_header.txt
> +Copyright 2014-present Palantir Technologies
Facebook uses this style in their react headers: e.g. https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.js

2017-02-06 19:06 UTC, themadcreator approved these changes
I kind of wanted:
```
/**
 * Copyright ...
 */
```
but this is fine

2017-02-06 21:26 UTC, adidahiya requested changes
if we're making changes here, might as well do JSDoc license headers. http://usejsdoc.org/tags-license.html

2017-02-07 18:01 UTC, hellochar commented
@adidahiya @themadcreator how's that?

2017-02-08 10:33 UTC, adidahiya approved these changes

2017-02-08 12:58 UTC, merged