Category axis doesn't consider offscreen labels when requesting space
palantir/plottable pull request #3223
Opened 2017-02-07 17:51 UTC by hellochar

Category Axis will now only render/consider the ticks that will actually be drawn. This fixes a bug where pan/zoomed category axes might have a lot of unnecessary whitespace.

2017-02-07 18:34 UTC, adidahiya commented
screencaps / gifs? is this smooth now?

2017-02-07 20:05 UTC, themadcreator requested changes
Just a comment update request

2017-02-07 20:05 UTC, themadcreator commented on src/axes/categoryAxis.ts
> +  public getDownsampleInfo(scale: Scales.Category = <Scales.Category> this._scale, domain = scale.invertRange()): DownsampleInfo {
I didn't know you could reference previous args in later default args. Neat

2017-02-07 20:05 UTC, themadcreator commented on src/axes/categoryAxis.ts
> -    this._hideOverflowingTickLabels();
Why don't we need this anymore?

2017-02-07 20:05 UTC, themadcreator commented on src/scales/categoryScale.ts
> +   * Return a clone of this category scale without any included values providers.
I'm glad you're encapsulating this into a method. Can you include in this comment some info about what **IS** included in the partial "clone" of this scale.

2017-02-08 13:20 UTC, hellochar commented
There's some jank for how this behaves when pan/zoom and downsampling are enabled:

Zoom suddenly stops because the axis grows:
<img src="https://cloud.githubusercontent.com/assets/1079495/22738776/1cc806a8-ee09-11e6-969d-08606e117f58.gif" width="400"/>

Layout jankily jumps around because the specific labels being drawn (and therefor the height) change while panning:
<img src="https://cloud.githubusercontent.com/assets/1079495/22738779/1f847516-ee09-11e6-9e8c-0b869ba90584.gif" width="400" />

2017-02-08 16:14 UTC, helenkg commented
@hellochar I would assume once we do vertical labels and truncate them at fixed height, the height of individual labels won't change when zooming and panning?

2017-02-08 19:44 UTC, adidahiya commented
> once we do vertical labels and truncate them at fixed height

@helenkg this still won't fix the problem because some labels might be at the full height & truncated while others are not close to the truncation limit

@hellochar in general I'm not a fan of the behavior shown in the above gifs; what if you waited until pan/zoom completed before redrawing the layout?

2017-02-08 20:31 UTC, hellochar commented
@adidahiya not a fan of tying re-compute to panzoom interactions since that adds a lot of complexity. Let me try throttling requestedSpace() and see how that feels

2017-02-08 21:31 UTC, adidahiya commented
@hellochar can you elaborate on the code complexity just a bit? I think it could work out really well actually from a user's perspective.

Also curious if @pkwi has any thoughts

2017-02-08 22:00 UTC, hellochar commented
throttling doesn't work. With maxWidth and 90 degree angles, it still has some jank:

<img src="https://cloud.githubusercontent.com/assets/1079495/22759313/44f99f80-ee52-11e6-879c-b9ac3bd7e8ab.gif" width="300" />

2017-02-10 13:31 UTC, hellochar commented
@adidahiya here's "wait until pan is finished to recalculate":

![ezgif com-video-to-gif 9](https://cloud.githubusercontent.com/assets/1079495/22828381/35771e06-ef9d-11e6-9514-24ea761c72b5.gif)

Definitely feels better. The zoom issue is still there but I think I'm okay with leaving that in until people complain.

2017-02-10 20:38 UTC, themadcreator commented
Okay, i think i finally get how this works. I was just missing the fact that your pass in the value of `.invertRange()` as the domain. Looks good, and this should work really well with sheared ticks

2017-02-10 20:38 UTC, themadcreator approved these changes

2017-02-10 20:41 UTC, themadcreator commented
I'm gonna merge this because I want to pull these changes in to test sheared ticks. If there are still more changes to address the "jank", that can be a followup PR

2017-02-10 20:41 UTC, merged