Nearest entity data / pixel space option
palantir/plottable pull request #3245
Opened 2017-02-24 23:15 UTC by leebyp

As per the threads in #3241 
- There should just be a flag of which "space" to use to find the nearest entity instead of trying to second guess what the consumer wants.
- Because of the reasoning for changes in #3159 for pan/zoom interaction, we're constrained in entities only having their datum and not their pixel position anymore.
- There are a bunch of places where we were actually comparing pixel `Points` or data `Points` in calculations eg. in `_entityVisibleOnPlot` - passing around `transformPoint` fixes it up (and just defaults to an identity function)

2017-02-27 20:59 UTC, thelastnode commented
This is blocking us from upgrading from 2.2.0, would love to have it merged :)

2017-03-01 00:24 UTC, leebyp commented
looks like nearest entity on segment plots and pie plots are broken already and should be fixed in another PR

2017-03-06 21:02 UTC, themadcreator requested changes

2017-03-06 21:02 UTC, themadcreator commented on quicktests/overlaying/tests/functional/nearestEntity.js
> +        .x(function (d) { return d.x; }, xScale)
weird space, also you could probably just use an arrow function here

2017-03-06 21:02 UTC, themadcreator commented on quicktests/overlaying/tests/functional/nearestEntity.js
> +function makeData() {
where are the actual tests here?

2017-03-06 21:02 UTC, themadcreator commented on quicktests/overlaying/tests/functional/nearestEntity.js
> +function makeData() {
Or is this just for interactive testing in the browser?

2017-03-06 21:02 UTC, themadcreator commented on src/plots/plot.ts
> +        const entityPoint = this._pixelPoint(entity.datum, entity.index, entity.dataset);
Okay, i'd like the change how this works slightly.  Plots.LightweightPlotEntity already has a `position` prop. But if that is not a pixel position, what is it? There are no docs on the prop.

If `position` is computed incorrectly then we should fix that. If it's a separate kind of "Point" (like not in screen space), then i vote that we add another prop to the lightweight entity for `pixelPosition`. Example see xyplot's `_buildLightweightPlotEntities` method.

2017-03-06 21:09 UTC, leebyp commented on quicktests/overlaying/tests/functional/nearestEntity.js
> +function makeData() {
yeah these are for manual in browser testing

2017-03-06 21:15 UTC, leebyp commented on src/plots/plot.ts
> +        const entityPoint = this._pixelPoint(entity.datum, entity.index, entity.dataset);
#3159 from @CalvinFernandez specifically shies away from storing `position` as the pixel position for pan / zoom interactions. Position likely doesn't mean anything anymore, will look into that.

I haven't looked into experimenting with changing the `lightweightplotentities` and how it interacts with the pan / zoom piece but can do.

2017-03-06 21:25 UTC, themadcreator commented on src/plots/plot.ts
> +        const entityPoint = this._pixelPoint(entity.datum, entity.index, entity.dataset);
Wait, doesn't this line indicate that position `SHOULD` be the pixel point? https://github.com/palantir/plottable/pull/3159/files#diff-47fd4a46971263fdadcbb8b6b09117c1R472

2017-03-07 17:29 UTC, closed without merging