Labels position
palantir/plottable pull request #3319
Opened 2017-03-29 15:36 UTC by leebyp

I can't quite figure out why we have a difference between `labelContainerOrigin` and `labelOrigin` so have just used the existing code as guidance.

2017-03-29 18:18 UTC, leebyp commented
[Positioned labels](https://392-16149854-gh.circle-artifacts.com/0/home/ubuntu/plottable/quicktests/dev/index.html#basic/label_bars)

2017-03-29 20:05 UTC, themadcreator requested changes
_drawLabel is now like 200 lines long. Can you please extract those x/y positioning functions? I know they modify scope variables, but that method is just too huge.

2017-03-29 21:38 UTC, hellochar requested changes
I thought in the stacked case the designs called for per-stack labels to be centered in the stack, plus a total outside the stack, whereas this puts all of them on top? And then for stacks with only one stack, or normal bar charts (or clustered), we just show the value of the bar outside the bar?

2017-03-29 21:38 UTC, hellochar commented on src/plots/barPlot.ts
> +          switch (position) {
DRY the vertical and horizontal cases please, and move the label drawing logic into its own method imo

2017-03-30 10:10 UTC, leebyp commented
@hellochar the positioning of the labels feels like a logical configuration point we can leave to the user

2017-04-01 18:46 UTC, leebyp commented
Extracting out the huge `drawLabel` to more specific methods. Some repetition in variables within the methods, but this avoid any subtle mutations and is now much more obvious which variables are being used in the calculations.

2017-04-27 00:45 UTC, hellochar approved these changes

2017-04-27 00:46 UTC, hellochar commented
@themadcreator wanna take a quick pass at this? Looks quite close so it'd be nice to get in for 3.1.0

2017-04-27 22:19 UTC, themadcreator approved these changes

2017-04-27 23:06 UTC, merged