Allow null in Table constructor type.
palantir/plottable pull request #3358
Opened 2017-06-04 16:02 UTC by devnev

The documentation and implementation currently permit null, but the actual constructor type requires all cells to be valid components.

2017-06-04 16:02 UTC, palantirtech commented
Thanks for your interest in [palantir/plottable](https://github.com/palantir/plottable), @devnev! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2017-06-05 20:17 UTC, hellochar requested changes
Much welcomed PR, thanks for submitting!

2017-06-05 20:17 UTC, hellochar commented on src/components/table.ts
> +  constructor(rows: (Component|null)[][] = []) {
Lets also allow `undefined`

2017-06-10 00:08 UTC, hellochar commented
Went ahead and fixed it in Github, cheers :)

2017-06-10 00:08 UTC, merged

2017-06-10 12:48 UTC, devnev commented
Hey @hellochar, thanks for the quick turnaround. Worth noting that the implementation does not check for `undefined`, only for `null`, so the new type specification doesn't match the implementation. The documentation also mentions `null can be used if a cell is empty.`, but doesn't specify the behaviour for `undefined`.

2017-06-15 18:32 UTC, hellochar commented
Absolutely correct, good eye 😉  we consciously allow `undefined` by using double-equals (`== null`) to be more user friendly/robust, but it's not documented since we don't want to necessarily encourage it