memoize compute extents
palantir/plottable pull request #3385
Opened 2017-07-27 00:41 UTC by hellochar

Memoize calls to computing the plot extents (which does a linear pass through the data), improving perf. This also lets us delete a bunch of _update methods and move away from the "update" paradigm

2017-07-27 17:36 UTC, themadcreator approved these changes

2017-07-27 17:36 UTC, themadcreator commented on src/memoize/memoize.ts
> + * Copyright 2014-present Palantir Technologies
technically i think these should be 2017-present

2017-08-07 22:15 UTC, themadcreator requested changes
some minor requests and questions

2017-08-07 22:15 UTC, themadcreator commented on src/memoize/memThunk.ts
> +    compute: (this: void, arg1: I1, arg2: I2, arg3: I3, arg4: I4) => O,
you know what we need? variadic template types. dang.

2017-08-07 22:15 UTC, themadcreator commented on src/memoize/signature.ts
> +
`export type ISignatureRecord = Record<string, Signature>;`

2017-08-07 22:15 UTC, themadcreator commented on src/memoize/signature.ts
> +        // debugger;
stray debugger

2017-08-07 22:15 UTC, themadcreator commented on src/memoize/signature.ts
> +export function sign<T>(a: T): Signature {
since you're not using T anywhere else, isn't this as good as `any` ?

2017-08-07 22:15 UTC, themadcreator commented on src/memoize/memoize.ts
> +export function memoize<F extends Function>(compute: F): MemoizedFunction<F> {
alright, so this is the actual memoize function that will be the main first thing people read. i'd like the comment to tell me:

how to use it (short code example).
what sort of pitfalls there are (vis a vis signatures). a warning that arguments that are not shallow comparable may need a custom signature.
also,  what memoization locking is and why you would want to use it.

2017-08-07 22:15 UTC, themadcreator commented on quicktests/overlaying/tests/realistic/scatter_bar.js
> +    .x2(function(d) { return d.leadership; })
why was this necessary? doesn't calling `.x2` here re-use the `xScale` from the call to `.x` above anyway?

2017-08-07 22:15 UTC, themadcreator commented on src/memoize/memoize.ts
> +    memoizeFn.logPerformance = function() {
since this is debugging only, i doubt you'd care to turn it off, but it might be worth taking an optional argument.

2017-08-07 22:15 UTC, themadcreator commented on src/memoize/memoize.ts
> +    memoizeFn.logPerformance = function() {
`.logPerformance(logit = true)`

2017-08-07 22:15 UTC, themadcreator commented on src/plots/plot.ts
> +    if (this._attrExtents[attr] == null) {
does this ever need to be overrided or deleted once it's defined?

2017-08-07 22:15 UTC, themadcreator commented on src/plots/plot.ts
> +  public static _scaledAccessor<D, R>(binding: Plots.IAccessorScaleBinding<D, R>) {
public _methodName ? we should rename without underscore. or can we get away with protected?

2017-08-07 22:15 UTC, themadcreator commented on src/plots/plot.ts
> +function _computeExtent(
no need to underscore for unexported functions, i think

2017-08-07 22:15 UTC, themadcreator commented on src/plots/plot.ts
> +function _computeExtent(
or do we do that elsewhere in plottable?

2017-08-07 22:15 UTC, themadcreator commented on src/plots/stackedAreaPlot.ts
> +      (datasets, keyAccessor, valueAccessor, stackingOrder) => {
this is basically reselect's API. should we just us reselect?

2017-08-07 22:15 UTC, themadcreator commented on src/plots/stackedBarPlot.ts
> +import { memThunk, Thunk } from "../memoize/index";
don't think you need the `/index` ?

2017-08-07 22:15 UTC, themadcreator commented on test/memoize/memoizeTests.ts
> +describe("memoize()", () => {
💯

2017-08-07 22:15 UTC, themadcreator commented on src/plots/stackedAreaPlot.ts
> +      (datasets, keyAccessor, valueAccessor, stackingOrder) => {
i guess it won't quite work if we don't do immutable objects

2017-08-07 23:09 UTC, hellochar commented on quicktests/overlaying/tests/realistic/scatter_bar.js
> +    .x2(function(d) { return d.leadership; })
The second argument to `x2` is now the `postScale` function; this was breaking the examples

2017-08-07 23:22 UTC, hellochar commented on src/plots/plot.ts
> +    if (this._attrExtents[attr] == null) {
Nope, this should be defined the same way for all attrs (and will always be defined that way)

2017-08-07 23:26 UTC, hellochar commented on src/plots/stackedAreaPlot.ts
> +      (datasets, keyAccessor, valueAccessor, stackingOrder) => {
Yeah we basically rewrote reselect

2017-08-07 23:34 UTC, themadcreator commented on quicktests/overlaying/tests/realistic/scatter_bar.js
> +    .x2(function(d) { return d.leadership; })
oh, okay

2017-08-07 23:35 UTC, themadcreator commented on src/plots/stackedAreaPlot.ts
> +      (datasets, keyAccessor, valueAccessor, stackingOrder) => {
rereselect

2017-08-07 23:40 UTC, themadcreator approved these changes

2017-08-07 23:42 UTC, merged