stroke-dasharray support for lineDrawer
palantir/plottable pull request #3421
Opened 2017-11-15 22:07 UTC by waltonseymour

This adds support for dashed lines in canvas rendering.

2017-11-15 22:07 UTC, palantirtech commented
Thanks for your interest in [palantir/plottable](https://github.com/palantir/plottable), @waltonseymour! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2017-11-15 22:30 UTC, themadcreator commented on src/drawers/canvasDrawer.ts
> +      return cleaned.split(",").map((x: string) => parseInt(x, 10));
I think you can use regexp's in `string.split`, so instead of doing a replace then split i think you could just do `rawValue.split(/[ ,]+/)`

2017-11-15 22:31 UTC, themadcreator commented on src/drawers/canvasDrawer.ts
> +      return cleaned.split(",").map((x: string) => parseInt(x, 10));
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#Parameters

2017-11-15 22:34 UTC, themadcreator requested changes
Okay, I think I'd like to use the different split syntax, but otherwise this looks like a simple quality contribution.Thank you!

2017-11-15 22:35 UTC, themadcreator commented
oh, dang, so fast

2017-11-15 22:36 UTC, themadcreator approved these changes
Okay, code looks good, just need the CLA signed and we can merge

2017-11-15 22:36 UTC, hellochar reviewed
Looks good from my end!

2017-11-16 21:39 UTC, themadcreator commented
poke @waltonseymour, just need you to agree to the CLA (https://cla.palantir.com/)

2017-11-17 18:59 UTC, waltonseymour commented
Working on getting that signed and sent over. I'll ping this thread when that's done.

2017-11-21 14:56 UTC, waltonseymour commented
I sent the signed CLA to `opensource@palantir.com`. Haven't received a response yet. Let me know if you need anything else from my end.

2017-11-21 23:25 UTC, waltonseymour commented
Should be GTG now

2017-11-27 18:43 UTC, merged