Add optional offset for tickGenerator
palantir/plottable pull request #3430
Opened 2017-12-20 10:51 UTC by SergeKireev

This is useful when handling dates through intervalTickGenerator, as the ticks are offset from whole intervals (n => n*DAY_MILLIS with DAY_MILLIS = 24*3600*1000)  by an hour.

2017-12-20 10:51 UTC, palantirtech commented
Thanks for your interest in [palantir/plottable](https://github.com/palantir/plottable), @SergeKireev! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2018-03-09 20:09 UTC, themadcreator requested changes

2018-03-09 20:09 UTC, themadcreator commented on src/scales/tickGenerators.ts
> -    const highTicks = high % interval === 0 ? [] : [high];
it looks like removing the highTicks here breaks the unit tests

2018-05-02 18:17 UTC, themadcreator commented
Closed due to lack of activity

2018-05-02 18:17 UTC, closed without merging