For-each loop optimization and memoize normalizeKey
palantir/plottable pull request #3469
Opened 2018-05-30 20:58 UTC by philcchen

Optimization around for-each loops (https://jsperf.com/fast-array-foreach ) for a comparison. 

Memoization of `normalizeKey` function, would like a sanity check to make sure that `normalizeKey` never gets called with a mutable object.

2018-05-30 20:59 UTC, philcchen commented on src/utils/stackingUtils.ts
> +export const normalizeKey = lMemoize((key: any) => {
@themadcreator I _believe_ that any `key` passed in here should be immutable, but given it's typed as `any`, would want a sanity check?

2018-05-30 22:55 UTC, themadcreator commented on src/utils/stackingUtils.ts
> +export const normalizeKey = lMemoize((key: any) => {
I'm not sure this memoization will actually help because in order to create the cache key and store the value, it will convert the argument into a `Map` key which might be just as slow as the `String(key)` below

2018-05-30 22:55 UTC, themadcreator commented on src/utils/stackingUtils.ts
> +const lMemoize = require("lodash.memoize");
even though this keeps the library size smaller, i think i'd prefer to use the normal import syntax. Unfortunately the modular lodash packages don't support `import` statements for some reason.

2018-05-30 23:36 UTC, themadcreator commented on src/utils/stackingUtils.ts
> +const lMemoize = require("lodash.memoize");
There are some instructions on how to get treeshaking to work with lodash, but i couldn't get it to work

https://medium.com/@martin_hotell/tree-shake-lodash-with-webpack-jest-and-typescript-2734fa13b5cd

2018-05-30 23:40 UTC, themadcreator requested changes

2018-05-30 23:40 UTC, themadcreator commented on src/drawers/rectangleDrawer.ts
>        return;
`return` -> `continue`

2018-05-30 23:40 UTC, themadcreator commented on src/plots/piePlot.ts
>          return;
`return` -> `continue`

2018-05-30 23:40 UTC, themadcreator commented on src/plots/plot.ts
>            return;
`return` -> `continue`

2018-05-30 23:40 UTC, themadcreator commented on src/plots/rectanglePlot.ts
>        if (datum == null) {
`return` -> `continue`

2018-05-30 23:40 UTC, themadcreator commented on src/plots/scatterPlot.ts
>            return;
`return` -> `continue`

2018-05-30 23:40 UTC, themadcreator commented on src/utils/stackingUtils.ts
>          return;
`return` -> `continue`

2018-05-31 01:41 UTC, philcchen commented on src/plots/rectanglePlot.ts
>        if (datum == null) {
(addressed, but diff doesn't recognize)

2018-05-31 21:56 UTC, themadcreator approved these changes

2018-05-31 21:56 UTC, merged